Fixed build issues
note: the wierd reordering of #includes throughout the project was to
fix this issue:

"
/usr/include/python3.4m/object.h:435:23: error: expected member name or
';' after declaration specifiers
      PyType_Slot *slots;
      ~~~~~~~~~~~       ^
	      1 error generated.
"

it turned out to be related to the 'slots' macro used by qt - any place
where we included qt stuff before including python, this error would pop
up and prevent compilation


Former-commit-id: c038ae29a73c70792a76a0bdb0dce3f1f0d8176e